<?php

namespace Database\Factories;

use App\Models\MobileDetail;
use App\Models\Product;
use Illuminate\Database\Eloquent\Factories\Factory;

class MobileDetailFactory extends Factory
{
    protected $model = MobileDetail::class;

    public function definition()
    {
        return [
            // product_id will usually be set when calling the factory
            // 'product_id' => Product::factory(), 
            'color' => $this->faker->optional()->colorName,
            'storage' => $this->faker->optional()->randomElement(['64GB', '128GB', '256GB', '512GB']),
            'battery_health' => $this->faker->optional()->numberBetween(70, 100),
            'ram' => $this->faker->optional()->randomElement(['4GB', '6GB', '8GB', '12GB']),
            'gpu' => $this->faker->optional()->word,
            'cpu' => $this->faker->optional()->words(2, true),
            'condition' => $this->faker->optional()->randomElement(['New', 'Used - Like New', 'Used - Good', 'Used - Fair']),
            'device_description' => $this->faker->optional()->sentence,
            'has_box' => $this->faker->boolean(70), // 70% chance of having a box
            
            // New fields (paths will be placeholders, actual files not generated by factory)
            'qrcode' => null, // QR code path, should be generated by the system later
            'scan_id' => $this->faker->optional(0.3)->filePath(null, 'scanned_id.jpg'), // 30% chance
            'scan_documents' => $this->faker->optional(0.2)->filePath(null, 'scanned_doc.pdf'), // 20% chance
        ];
    }
}
